#ifndef DRIVECONTROLLER_GLOBAL_H
#define DRIVECONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRIVECONTROLLER_LIBRARY)
#  define DRIVECONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DRIVECONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DRIVECONTROLLER_GLOBAL_H
