#ifndef MISSIONCONTROL_GLOBAL_H
#define MISSIONCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MISSIONCONTROL_LIBRARY)
#  define MISSIONCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MISSIONCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MISSIONCONTROL_GLOBAL_H
