#ifndef VIDEOSERVER_GLOBAL_H
#define VIDEOSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIDEOSERVER_LIBRARY)
#  define VIDEOSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIDEOSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOSERVER_GLOBAL_H
